displayName: NoaaS Default Route
type: middleware
import: github.com/r-win/noaas-default-route

summary: Displays messages from naas.isalman.dev with client-side fetching

testData:
  APIEndpoint: https://naas.isalman.dev/no
  DefaultMessage: Go Away
